# Generated by Django 2.0.2 on 2018-03-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='sgpg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=50)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(max_length=15)),
                ('parents_name', models.CharField(max_length=30)),
                ('parents_phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=250)),
                ('joining_date', models.CharField(max_length=50)),
                ('deposit', models.CharField(max_length=8)),
                ('rent', models.CharField(max_length=8)),
                ('pending', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sgpg',
            },
        ),
    ]
